version: '3'

services:
  db:
    image: postgres
    container_name: nestjs-task-manager-postgres
    restart: always
    tty: true
    ports:
      - '${POSTGRES_PORT}:5432'
    # volumes:
    #   - ./task-manager-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}

  app:
    image: nestjs-task-manager-app
    build: .
    tty: true
    links:
      - db
    volumes:
      - .:/nestjs-task-manager
      - ./node_modules:/nestjs-task-manager/node_modules
    ports:
      - ${PORT}:3000
    depends_on:
      - db
    restart: always
    command: bash -c "npm run start:dev"
