version: 2.1

orbs:
  node: circleci/node@4.7
  heroku: circleci/heroku@1.2.6

jobs:
  # ===========================
  # Tests:
  # ===========================
  run-tests:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run Unit Tests
          command: yarn test
      - run:
          name: Run E2E Tests
          command: yarn test:e2e

  # ===========================
  # Deploy ( Homolog ) Heroku:
  # ===========================
  heroku-deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - heroku/deploy-via-git:
          api-key: ${{secrets.HEROKU_API_KEY}}
          app-name: ${{secrets.HEROKU_APP_NAME}}
          branch: master
          filters:
            branches:
              only:
                - master

workflows:
  sample:
    jobs:
      - run-tests
      - heroku-deploy
